source = ~/.config/hypr/modules/themes/mocha.conf

accent = $pink
accent_secondary = $mauve
base = $mantle
background = $base

font_family = JetBrainsMono Nerd Font Mono
font_family_monospace = JetBrainsMono Nerd Font Mono
font_size = 14
text = $text

